<style>
	p{
 margin-bottom:1em;
}




.h1, h1 {
  font-size: 2em
}

.h2, h2 {
  font-size: 1.8em
}

.h3, h3 {
  font-size: 1.6em
}

.h4, h4 {
  font-size: 1.4em
}

.h5, h5 {
  font-size: 1.2em
}

.h6, h6 {
  font-size: 1em
}

.nav, .navbar {
  font-size: 1em
}

.navbar-brand {
  font-size: 1.2em
}

.control-label, .form-control, input, label {
  font-size: 1em
}

.form-control {
  padding: .4em .8em;//.375em .75em;
  height: 2.5em;//2.125em
}

.input-lg {
  font-size: 1.2em;
  padding: .625em 1em;
  height: 2.875em
}

.input-sm {
  height: 2.2em;//2em;
  font-size: .85em;
  padding: .3125em .625em
}

.label {
  line-height: 2
}

.badge {
  font-size: .85em;
  min-width: 1em;
  padding: .225em .7em
}

.dropdown-header, .dropdown-menu {
  font-size: 1em
}

.panel-title {
  font-size: 1em
}

.jumbotron {
  font-size: 1em
}

.jumbotron .h1, .jumbotron h1 {
  font-size: 3.9375em
}

.jumbotron p {
  font-size: 1.3125em
}
/*Begin data table tweaks*/
.table button.btn-danger{
  background-color:#661312;
  border-color:#661312;
}
.table button.btn-danger:hover{
  background-color:#912222;
  border-color:#912222;
}
button.btn:hover, button.btn:focus{
  text-decoration:underline;
}
.paginate_button a:hover,
.paginate_button a:focus,
.paginate_button.active a{
  text-decoration:underline;
}
.table-striped > tbody > tr:nth-of-type(2n+1){
  background-color:#f0f0f0;
}
th:focus, td:focus, tr:focus{
  outline: 1px solid #66AFE9;
  box-shadow:0px 1px 1px rgba(0, 0, 0, 0.075) inset, 0px 0px 8px rgba(102, 175, 233, 0.6);
}
    .vvv{
      font-size:12px;
      background-color: white;
	  text-align:center;
    }
    .vvv2{
      color:black;
      background-color: white;
      padding: 30px;
      border-radius:10px;
    }
	.button1 {
		padding: 5px;
		width: 40px;
		}
</style>
		
		
 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <span class="light-logo"><img src="<?php echo base_url();?>./help/page/img/xnxx.png"height="20" alt="logo"></span>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
        <li class="breadcrumb-item active">Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
  <div class="vvv2">
	<table id="autoGeneratedID" role="grid" class="table table-striped table-bordered vvv">
    <thead>
        <tr>
    <th>Username</th>
    <th>Password</th>
    <th>Name</th>
    <th>Group</th>
    <th>Status</th>
    <th>Date Created</th>
    <th>Action</th>
  </tr>
    </thead>
<tbody>
												
		<?php
	  		$list_user = array_filter($list_user);
					if (!empty($list_user)) {
						 foreach ($list_user as $user_detail){
							 if ($user_detail['del_flag'] == '1'){ 
								if ($user_detail['enable'] == '1'){ 
									$txt_status = '<span class="label label-sm label-success">Enable</span>'; 
									$txt_color = '#0EC952';
													  
								}else{
									$txt_status = '<span class="label label-sm label-warning">Disable</span>'; 
									$txt_color = '#FF0000'; 
									 }?>
				<tr>
				<td><?php echo $user_detail['username'];?></td>
				<td><?php echo $user_detail['password'];?></td>
				<td><?php echo $user_detail['firstname'].'  '.$user_detail['lastname'];?></td>
				<td style="text-align:center;"><?php echo $user_detail['group_name'];?></td>
				<td style="text-align:center;"><?php echo '<span style="color:'.$txt_color.'">'.$txt_status.'</span>';?></td>
				<td style="text-align:center;"> <?php echo date('Y-m-d H:i:s', strtotime($user_detail['date_create']));?></td>
				<td>
				<a data-original-title='Rule' onclick="javascript:window.location='<?php echo base_url().'user/rule/'.$user_detail['su_id'];?>';">
                <button class="btn bg-success button1"><i class="fas fa-edit "></i></button>
              	</a>
			<?php
				if($user_detail['enable'] == 1){?>
					<a data-original-title='Disable' onclick="javascript:window.location='<?php echo base_url().'User/disable/'.$user_detail['su_id'];?>';">
                    <button class="btn bg-secondary button1"><i class="fas fa-user-alt-slash"></i></button>
              		</a>											
			<?php }else{ ?>
					<a data-original-title='Enable' onclick="javascript:window.location='<?php echo base_url().'user/enable/'.$user_detail['su_id'];?>';">
                    <button class="btn bg-warning button1"><i class="fas fa-user-alt"></i></button>
              		</a>										
			<?php } ?>
					<a data-original-title='Delete' onclick="javascript:if(confirm('คุณต้องการลบรายการนี้ใช่หรือไม่?')){ window.location='<?php echo site_url('table/delete/').$user_detail['su_id'];?>'; }else{ return false; }">
                    <button class="btn bg-danger button1"><i class="fas fa-trash-alt "></i></button>
              		</a>
				</td>
				</tr>
			<?php }} } ?>
			</tbody>
  </table>
  </div>
	</section>
    <!-- /.content -->
  </div>