<!DOCTYPE html>
<html lang="en">
<?php $this->load->helper('url'); ?>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta charset="utf-8" />
	<title><?php echo $page_title; ?></title>
	<link rel="icon" href="<?php echo base_url(); ?>./themes/softmat/img/tbk.png">
	<meta name="description" content="User login page" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
	<link rel="stylesheet" href="<?php echo base_url() . $css_url; ?>bootstrap.css" />
	<link rel="stylesheet" href="<?php echo base_url() . $css_url; ?>bootstrap-extend.css" />
	<link rel="stylesheet" href="<?php echo base_url() . $css_url; ?>master_style.css" />
	<link rel="stylesheet" href="<?php echo base_url() . $css_url; ?>_all-skins.css" />
	<link rel="stylesheet" href="<?php echo base_url() . $css_url; ?>weather-icons.css" />
	<link rel="stylesheet" href="<?php echo base_url() . $css_url; ?>jquery-jvectormap-2.0.2.css" />
	<link rel="stylesheet" href="<?php echo base_url() . $css_url; ?>morris.css" />
	<link rel="stylesheet" href="<?php echo base_url() . $css_url; ?>all.min.css" />
	<link rel="stylesheet" href="<?php echo base_url() . $css_url; ?>font-awesome.min.css" />
	<link rel="stylesheet" href="<?php echo base_url() . $css_url; ?>ace.min.css" />

</head>

<body class="no-skin">

	<?php echo $page_header; ?>

	<?php echo $page_menu; ?>




	<?php echo $page_content; ?>



	<?php echo $page_footer; ?>


	<script src="<?php echo base_url() . $js_url; ?>jquery-3.3.1.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>jquery-ui.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>popper.min.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>bootstrap.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>jquery.slimscroll.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>fastclick.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>jquery.sparkline.min.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>echarts-en.min.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>echarts-liquidfill.min.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>jquery.peity.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>raphael.min.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>morris.min.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>jquery-jvectormap-2.0.2.min.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>jquery-jvectormap-us-aea-en.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>template.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>dashboard.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>demo.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>bootstrap.min.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>ace.min.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>all.min.js"></script>

	<script src="<?php echo base_url() . $js_url; ?>jquery.dataTables.min.js"></script>
	<script src="<?php echo base_url() . $js_url; ?>ace.min.js"></script>

	<script>
		$('#autoGeneratedID').DataTable({
			"pageLength": 25,
			"destroy": true,
			colReorder: true,
			dom: '<"toolbar">lBfrtip',
			buttons: [{
					extend: 'colvis',
					text: 'Show/Hide Column'
				},
				{
					extend: 'copy',
					text: 'Copy all',
					exportOptions: {
						modifier: {
							selected: null
						}
					}
				},
				{
					extend: 'copy',
					text: 'Copy selected'
				},
				{
					extend: 'csv',
					text: 'CSV all',
					exportOptions: {
						modifier: {
							selected: null
						}
					}
				},
				{
					extend: 'csv',
					text: 'CSV selected'
				},
				{
					extend: 'excel',
					text: 'EXCEL all',
					exportOptions: {
						modifier: {
							selected: null
						}
					}
				},
				{
					extend: 'excel',
					text: 'EXCEL selected'
				},
				{
					extend: 'pdf',
					text: 'PDF all',
					exportOptions: {
						modifier: {
							selected: null
						}
					}
				},
				{
					extend: 'pdf',
					text: 'PDF selected'
				},
				{
					extend: 'print',
					text: 'Print all',
					exportOptions: {
						modifier: {
							selected: null
						}
					}
				},
				{
					extend: 'print',
					text: 'Print selected'
				}
				//'csv', 'excel', 'pdf', 'print'
			],
			select: 'multi',
			data: dataSet,
			//autoWidth: false,
			/*"fixedColumns": {
			    leftColumns:1
			},*/
			//"fixedHeader":true,
			//scrollX: true,
			//scrollY:true,
			// scrollx: "900px",
			//scrollY: "900px",
			//scrollCollapse: true,
			/*columnDefs: [
			    { width: '10%', 'targets': [0] },
			    { width: '10%', 'targets': [1] },
			    { width: '15%', 'targets': [2] },
			    { width: '5%', 'targets': [3] },
			    { width: '10%', 'targets': [4] },
			    { width: '10%', 'targets': [5] },
			    { width: '5%', 'targets': [6] },
			    { width: '5%', 'targets': [7] },
			    { width: '10%', 'targets': [8] },
			    { width: '5%', 'targets': [9] },
			    { width: '5%', 'targets': [10] },
			    { width: '5%', 'targets': [11] },
			    { width: '5%', 'targets': [12] }
			],*/
			columns: [{
					title: "Workspace"
				},
				{
					title: "Folder"
				},
				{
					title: "Folder Path"
				},
				{
					title: "Doc Name"
				},
				{
					title: "Doc Number"
				},
				{
					title: "Version"
				},
				{
					title: "Type"
				},
				{
					title: "Class"
				},
				{
					title: "Client"
				},
				{
					title: "Matter"
				},
				{
					title: "Author"
				},
				{
					title: "Last Edit Date"
				},
				{
					title: "Created Date"
				}
			]
		});
	</script>
</body>

</html>